# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
  AZURE_WEBAPP_NAME: unittestdemoapp
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 2.1
    - name: Restore dependencies
      run: dotnet restore ${{github.workspace}}/src/UnitTestDemo.WebUi/UnitTestDemo.WebUi.csproj
    - name: Build WebUi
      run: dotnet build ${{github.workspace}}/src/UnitTestDemo.WebUi/UnitTestDemo.WebUi.csproj --configuration Release --no-restore
    - name: Build Solution
      run: dotnet build ${{github.workspace}}/UnitTestDemo.sln
    - name: Test
      run: dotnet test ${{github.workspace}}/test/UnitTestDemo.Tests/UnitTestDemo.Tests.csproj --no-restore --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ${{github.workspace}}/src/UnitTestDemo.WebUi/UnitTestDemo.WebUi.csproj -c Release -o unittestdemo_pkg
    - name: Deploy to Azure App unittestdemoapp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{github.workspace}}/src/UnitTestDemo.WebUi/unittestdemo_pkg'
    
